name: nlp-project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - faiss-gpu
  - tokenizers>=0.19.0,<0.20.0
  - transformers>=4.36.0
  - sentence-transformers>=2.3.0 
  - huggingface_hub=0.21.0
  - accelerate
  - scikit-learn
  - pandas
  - tqdm
  - tensorboard
  - numpy
  - python-dotenv
  - matplotlib
  - nltk
  - sacrebleu
  - pip:
    - dexter-cqa